spring:
    #redis配置
    redis:
      host: 10.20.7.23
      port: 6379
      # REDIS (RedisProperties)
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器连接密码（默认为空）
      password:
      # 连接池最大连接数（使用负值表示没有限制）
      # 连接超时时间（毫秒）
      timeout: 0
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0